// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqXuls_8TSABnIIboO7mF6O-qsViDkts',
    appId: '1:1076600512881:web:9b402ccdce2146b99f96d0',
    messagingSenderId: '1076600512881',
    projectId: 'flutterapp-3839b',
    authDomain: 'flutterapp-3839b.firebaseapp.com',
    storageBucket: 'flutterapp-3839b.appspot.com',
    measurementId: 'G-EFS1T68FV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWUWCr0VPA4TehQzWKskwNvcz4_tSjyE',
    appId: '1:1076600512881:android:afcb29b21bb2b52b9f96d0',
    messagingSenderId: '1076600512881',
    projectId: 'flutterapp-3839b',
    storageBucket: 'flutterapp-3839b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6vcF96gG0r-5E9g8IrmvrugjdL-R-3Q',
    appId: '1:1076600512881:ios:a61f151991a8d8cf9f96d0',
    messagingSenderId: '1076600512881',
    projectId: 'flutterapp-3839b',
    storageBucket: 'flutterapp-3839b.appspot.com',
    iosClientId: '1076600512881-i8fsporrcqc1rmh2s4i0jde9o0tjvkfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testappcrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh6vcF96gG0r-5E9g8IrmvrugjdL-R-3Q',
    appId: '1:1076600512881:ios:a61f151991a8d8cf9f96d0',
    messagingSenderId: '1076600512881',
    projectId: 'flutterapp-3839b',
    storageBucket: 'flutterapp-3839b.appspot.com',
    iosClientId: '1076600512881-i8fsporrcqc1rmh2s4i0jde9o0tjvkfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testappcrud',
  );
}
